codecov:
  require_ci_to_pass: yes
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

github_checks:
  annotations: false

# Enable Codecov AI Reviewer for PR reviews
feature:
  ai:
    review:
      enabled: true
    tests:
      enabled: true
    show_help: true
