name: Run Tests and Upload Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --forceExit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}  # Optional if repo is public
          files: ./coverage/lcov.info           # Default Jest output file
          flags: unittests                      # Optional tagging
          name: codecov-coverage-report         # Optional name
          fail_ci_if_error: true
