name: Aszune AI Bot CI/CD

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --forceExit
        
      - name: Upload coverage to QLTY
        uses: qltysh/qlty-action/coverage@v1
        continue-on-error: true
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          fail_ci_if_error: false

  simple-test:
    name: Simple Test (No Coverage)
    runs-on: ubuntu-latest
    # Only run this job for feature branches that are not PRs
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests without coverage
        run: npm test -- --forceExit

# When ready to deploy the bot, you can uncomment and customize this job
#  deploy:
#    name: Deploy
#    needs: build-and-test
#    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#    runs-on: ubuntu-latest
#    
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Deploy to production
#        run: echo "Add your deployment steps here"
